### ISSUE TITLE
Daño enemigos (interacción entre enemigo y jugador)

### ISSUE THREAD

**Issue by SnowyPie** [Proyectos1-FDI-UCM/c2324-Grupo08#129]
**Descripción**
Al jugar y golpear a las ratas, estas parpadean para indicar que han sido golpeadas. En algunas ocasiones cuando se le golpea desde abajo, estas reciben el daño y entran en este estado de parpadeo, pero al acercarse el jugador no recibe daño pero si entra en el estado de parpadeo e invencibilidad.

**Pasos**
-Paso 1
Acercarte a una rata
-Paso 2
Golpearle desde abajo y acercarte para que te haga daño de colisión

**Captura de pantalla o vídeo**
Aquí el enlace al video grabado donde aparece el bug, se encuentra a los últimos segundos del video, cuando entra en la pantalla con la única rata y la botella.

https://youtu.be/0m0eln-vTPo

**Comment by Janime-UCM555** [comment]
El bug ya está resuelto.
El bug provenía de la desactivación del daño de la rata.
Cabía otra opción y es que estuviese superando el máximo de vida ya que al curar 2 de vida no teníamos limitada la curación asi que si recibías 1 de daño y superabas la vida máxima podías acumular daños que no se reflejaban
