### ISSUE TITLE
Como jugador quiero poder avanzar de pantallas y que la cámara me siga

### ISSUE THREAD

**Issue by eossheltgmail** [Proyectos1-FDI-UCM/c2324-Grupo08#2]
La cámara tendrá una vista elevada (top-down) y seguirá al jugador horizontalmente por las distintas pantallas. Cambiará a la siguiente cuando el jugador se acerque al borde derecho. Además, el avance del mapa será unidireccional, ya que el jugador no podrá volver a pantallas anteriores;

**Comment by MANK1NG** [comment]
https://github.com/Proyectos1-FDI-UCM/c2324-Grupo08/issues/8
https://github.com/Proyectos1-FDI-UCM/c2324-Grupo08/issues/9
https://github.com/Proyectos1-FDI-UCM/c2324-Grupo08/issues/10
